### ISSUE TITLE
MAX32651 DMA_UART0 / DMA_UART2 not work

### ISSUE THREAD

**Issue by michame951** [analogdevicesinc/msdk#1057] opened 2024-06-25 12:09 UTC
When I tested the MAX32651EVkit, DMA_UART0 and DMA_UART2 are not worked. if it is a general UART, it works normally. Please help me find out the issue.

The following link is UART project path.
C:\MaximSDK\Examples\MAX32650\UART

**Comment by michame951** [comment] 2024-08-08 13:08
I got support from ADI, maybe you can try it.
https://mega.nz/file/wRt3CAZI#suOhZLFAXMPQyWdkoNvYCWwdLjrSI7aAZ8oC3lz7vOg

**Comment by Jake-Carter** [comment] 2024-08-09 23:48
Thanks @michame951 I've been working with Ozan - see #1106 for the latest example code.

Closing as duplicate to consolidate to #1106, since the problem is really with the example

**Closed by Jake-Carter** 2024-08-09 23:48 UTC
